# Generated by Django 4.0.6 on 2023-02-21 07:01

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.CharField(choices=[('Done', 'Решен'), ('Not done', 'Не решен'), ('Freezed', 'Заморожен')], default=io.open, max_length=20),
        ),
    ]
