# Generated by Django 4.0.6 on 2023-02-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='feedback',
        ),
    ]
